Strengthen warnings about relying on Mask layout
rust-lang/portable-simd pull request #289
Opened 2022-07-01 02:29 UTC by thomcc

This makes it more clear that you can't rely on the layout of these, which seems worth doing given that the names vaguely suggest that you can (and the docs only clarify that you can't on `Mask` but not the `maskNxM` aliases).

Not tied to the specific wording here, and I'm not sure that it's actually worth clarifying that "yes, this includes `[iN; M]`", so I'm open to rewording. I do think we should have the caveat on the type aliases as well, though.

2022-07-01 03:56 UTC, calebzulawski requested changes

2022-07-01 03:56 UTC, calebzulawski commented on crates/core_simd/src/masks.rs
> -#[repr(transparent)]
I don't think you meant to delete this?

2022-07-21 01:01 UTC, thomcc commented on crates/core_simd/src/masks.rs
> -#[repr(transparent)]
Uhhhh nice catch.

2022-07-21 21:51 UTC, calebzulawski approved these changes

2022-07-21 21:53 UTC, merged

2022-07-21 22:26 UTC, workingjubilee commented
Thank you for following up on this!